name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag of this release
        required: true
        default: ''

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency: release

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: Test on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 & echo "Started xvfb"
        shell: bash
        if: ${{ success() && matrix.os == 'ubuntu-latest' }}
      - run: yarn install
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - run: yarn test
        env:
          DISPLAY: ":99.0"
  release:
    runs-on: ubuntu-latest
    needs: test
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: yarn install
      - run: npm install -g vsce
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: npm version ${{github.event.inputs.tag}} -m "Bump to %s" --git-tag-version false
      - run: vsce package
      - run: echo "VSIX_PATH=$(find . -maxdepth 1 -type f -iname "*.vsix" | head -1)" >> $GITHUB_ENV
      - run: echo "VSIX_NAME=$(basename $(find . -maxdepth 1 -type f -iname "*.vsix" | head -1))" >> $GITHUB_ENV
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
      - name: Update Changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{github.event.inputs.tag}}
      - name: Commit changelog
        run: |
          git add CHANGELOG.md
          git commit -m "Update Change Log to Release ${{github.event.inputs.tag}}"
      - run: git push origin main
      - name: Generate Changelog
        id: changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{github.event.inputs.tag}}
          path: ./CHANGELOG.md
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: '${{github.event.inputs.tag}}'
          release_name: 'Release ${{github.event.inputs.tag}}'
          body: |
            ${{ steps.changelog.outputs.changes }}

            See [Change Log](https://github.com/christianbraeunlich/vscode-git-multi-repo/blob/main/CHANGELOG.md) for details.
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.VSIX_PATH }}
          asset_name: ${{ env.VSIX_NAME }}
          asset_content_type: application/zip
      - name: Publish to Marketplace
        if: ${{ (startsWith(github.ref, 'refs/tags/')) }}
        run: vsce publish -pat ${{ secrets.ADO_PAT }}
        working-directory: ${{env.working-directory-vsc}}